---
title: "Plots for 2FF Figure"
output:
  html_document:
    keep_md: yes
    toc: yes
    theme: united
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

# General settings

```{r setup}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  include = TRUE,
  cache = TRUE,
  cache.lazy = FALSE,
  eval = TRUE,
  fig.width = 4 * (1 + sqrt(5)) / 2, 
  fig.height = 4,
  dpi = 700
)
knitr::opts_knit$set(root.dir = "~/Documents/01_repos/Glycoproteomics/")
```

```{r}
setwd("~/Documents/01_repos/Glycoproteomics/")
```


## Packages

```{r, message=F, warning =F, include=}
library(tidyverse)
library(ggplot2); theme_set(cowplot::theme_cowplot(font_size = 15))
library("reshape2")
library(ggrepel)
library(knitr)
library(Biostrings)
library(ComplexHeatmap)
library(viridis)

mutate <- dplyr::mutate
select <- dplyr::select
group_by <- dplyr::group_by
```

```{r}
options(ggplot2.discrete.colour= c("orange3", "darkslateblue", "darkred", "darkgreen", "darkgrey", "darkviolet"))
options(ggplot2.discrete.fill= c("orange3", "darkslateblue", "darkred", "darkgreen", "darkgrey", "darkviolet"))

order <- c("sialylated", "fucosylated", "high mannose", "complex/hybrid", "phospho", "paucimannose", "small")
pal <- c("lightgrey", "#d7301fff", "#377eb8ff", "#41ae76ff","#88419dff" ,"#ff7f00ff", "#ffe300ff","#f781bfff", "mediumseagreen", "grey")
names(pal) <- c("FP", "sialylated", "fucosylated", "high mannose", "complex/hybrid", "phospho", "paucimannose", "small", "hit", "no hit")

order_O <- c("O-sialylated", "O-fucosylated", "O-hexose", "O-hybrid", "O-phospho", "O-sulfated", "O-GlcNac")
pal_O <- c("lightgrey",  "#d7301fff", "#377eb8ff", "#41ae76ff","#88419dff" ,"#ff7f00ff", '#a65628ff',"#f781bfff")
names(pal_O) <- c("FP", "O-sialylated", "O-fucosylated", "O-hexose", "O-hybrid", "O-phospho", "O-sulfated", "O-GlcNac")
tilted <-  theme(axis.text.x = element_text(angle = 45, hjust =1, vjust = 1))
blank <- theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
```

```{r}
load("results/2024-09-26_res_2FF_timecourse.RData")
```


# A - workflow

in Inkscape 

# B - PCA

```{r}
pca_plot <- function(data_matrix, x, y, fx, fy, l, u, pal, title) {
  m <- data_matrix
  n_obs <- nrow(m)

  m <- m[matrixStats::rowVars(m, na.rm = T) %>%
    order(decreasing = T) %>%
    head((n_obs / 100) * 10), ]

  pca <- prcomp(t(m))

  data <- pca$x %>%
    as.data.frame() %>%
    rownames_to_column("sample") %>%
    select(sample, x = {{ x }}, y = {{ y }}) %>%
    separate(sample, c("timepoint", "condition", "replicate"), sep = "_", remove = F) %>%
    mutate(timepoint = factor(timepoint, levels = c("0h", "8h", "24h", "48h", "72h")))

  var <- (pca$sdev)^2 / sum(pca$sdev^2) * 100
  vx <- as.numeric(str_extract(as.character({{ x }}), "\\d"))
  vy <- as.numeric(str_extract(as.character({{ y }}), "\\d"))

  p <- data %>%
    ggplot(aes(x = x * fx, y = y * fy, fill = condition, shape = timepoint)) +
    geom_hline(yintercept = 0, colour = "grey", linetype = 3) +
    geom_vline(xintercept = 0, colour = "grey", linetype = 3) +
    geom_point(size = 4, stroke = 0.5, colour = "black") +
    scale_fill_manual(values = pal) +
    scale_shape_manual(values = c(21, 24, 22, 23, 25)) +
    cowplot::panel_border() +
    coord_fixed() +
    lims(x = c(l, u), y = c(l, u)) +
    # guides(fill = "none", shape = "none") +
    labs(
      x = paste0(as.character({{ x }}), " (", round(var[vx], digits = 1), "%)"),
      y = paste0(as.character({{ y }}), " (", round(var[vy], digits = 1), "%)"),
      subtitle = title
    )

  plot(p)
}
m <- res_2FF_timecourse$psm_corrected %>%
  mutate(sample = paste(timepoint, condition, replicate, sep = "_")) %>%
  dcast(
    ID ~ sample,
    value.var = "quant_corr", fill = NA
  ) %>%
  drop_na() %>%
  column_to_rownames("ID") %>%
  as.matrix()

pca_plot(m, "PC1", "PC2", 1, 1, -35, 25, pal = c("grey", "darkcyan"), "")
```

# C - clusters

```{r}
median_data <- res_2FF_timecourse$neural_clusters_alltreatmentdata %>%
  select(ID, cluster, contrast, logFC) %>%
  bind_rows(data.frame(cluster = 1, contrast = "0h", logFC = 0, ID = "dummy")) %>%
  complete(cluster, contrast, ID) %>%
  mutate(
    logFC = ifelse(contrast == "0h", 0, logFC),
    cluster = factor(cluster)
  ) %>%
  ungroup() %>%
  filter(ID != "dummy") %>%
  group_by(contrast, cluster) %>%
  summarise(logFC = mean(logFC, na.rm = T)) %>%
  mutate(contrast = as.numeric(str_remove(contrast, "h")))

res_2FF_timecourse$neural_clusters_alltreatmentdata %>%
  select(ID, cluster, contrast, logFC) %>%
  bind_rows(data.frame(cluster = 1, contrast = "0h", logFC = 0, ID = "dummy")) %>%
  complete(cluster, contrast, ID) %>%
  mutate(
    logFC = ifelse(contrast == "0h", 0, logFC),
    cluster = factor(cluster)
  ) %>%
  ungroup() %>%
  filter(ID != "dummy") %>%
  mutate(contrast = as.numeric(str_remove(contrast, "h"))) %>%
  ggplot(aes(contrast, logFC, colour = cluster)) +
  # geom_point(size = 0.1) +
  geom_hline(yintercept = c(0.6, -0.6), linetype = 3) +
  geom_hline(yintercept = 0, linetype = 1) +
  geom_line(aes(group = paste0(cluster, ID)), size = 0.1, alpha = 0.2) +
  geom_smooth(data = median_data, aes(group = cluster), colour = "black", size = 1.5) +
  geom_smooth(data = median_data, aes(group = cluster)) +
  scale_colour_manual(values = c("1" = "darkred", "2" = "indianred", "3" = "lightskyblue1", "4" = "dodgerblue4")) +
  # facet_wrap(~cluster) +
  labs(y = "log2 fold-change 2FF-control", x = "treatment duration [h]") 
```

# D - cluster composition

```{r}
res_2FF_timecourse$neural_clusters_alltreatmentdata %>%
  ggplot(aes(x = as.factor(cluster), fill = glycan_type)) +
  geom_bar(pos = "fill") +
  scale_fill_manual(values = pal) +
  labs(x = "cluster", y = "proportion of glycopeptides")
```

# E - fucosylation clusters

```{r}
median_data <- res_2FF_timecourse$neural_cluster_fuctreatmentdata %>%
  bind_rows(data.frame(cluster = 1, contrast = "0h", logFC = 0, ID = "dummy")) %>%
  complete(cluster, contrast, ID) %>%
  mutate(
    logFC = ifelse(contrast == "0h", 0, logFC),
    cluster = factor(cluster)
  ) %>%
  ungroup() %>%
  filter(ID != "dummy") %>%
  group_by(contrast, cluster) %>%
  summarise(logFC = mean(logFC, na.rm = T)) %>%
  mutate(contrast = as.numeric(str_remove(contrast, "h")))

res_2FF_timecourse$neural_cluster_fuctreatmentdata %>%
  bind_rows(data.frame(cluster = 1, contrast = "0h", logFC = 0, ID = "dummy")) %>%
  complete(cluster, contrast, ID) %>%
  mutate(
    logFC = ifelse(contrast == "0h", 0, logFC),
    cluster = factor(cluster)
  ) %>%
  ungroup() %>%
  filter(ID != "dummy") %>%
  mutate(contrast = as.numeric(str_remove(contrast, "h"))) %>%
  ggplot(aes(contrast, logFC, colour = cluster)) +
  # geom_point(size = 0.1) +
  geom_hline(yintercept = c(0.6, -0.6), linetype = 3) +
  geom_hline(yintercept = 0, linetype = 1) +
  geom_line(aes(group = paste0(cluster, ID)), size = 0.1, alpha = 0.4) +
  geom_line(data = median_data, aes(group = cluster), stat = "smooth", alpha = 1, size= 1, colour = "black") +
  geom_smooth(data = median_data, aes(group = cluster), size = 0.8) +
  scale_colour_manual(values = c("1" = "lightskyblue1", "2" = "dodgerblue3", "3" = "dodgerblue4")) +
  # facet_wrap(~cluster) +
  labs(y = "log2 fold-change 2FF-control", x = "treatment duration [h]") +
  cowplot::theme_cowplot() 
```

# F - protein heatmap

```{r}
tmp <- res_2FF_timecourse$neural_cluster_fuctreatmentdata %>%
  group_by(Protein.ID) %>%
  summarise(n = n_distinct(ID), n_clus = n_distinct(cluster)) %>% 
  filter(n >= 4 & n_clus == 3)

res_2FF_timecourse$neural_cluster_fuctreatmentdata %>%
  separate(ID, into = c("Protein.ID", "Gene", "Modified.Peptide", "Observed.Modifications", "glycan_type", "n_position"), sep = "_", remove = F) %>%
  filter(Protein.ID %in% tmp$Protein.ID) %>%
  group_by(cluster, Gene) %>%
  summarise(n = n(), mean_fc = mean(logFC)) %>%
  acast(Gene ~ cluster, value = "mean_fc", fill = 0) %>%
  ComplexHeatmap::Heatmap(row_names_gp = grid::gpar(fontsize = 8), col = circlize::colorRamp2(c(-2, 0, 2), c("dodgerblue4", "grey97", "darkred")), show_column_dend = F, show_row_dend = F, rect_gp = grid::gpar(col = "white", lwd = 1), name = "mean_logFC")
```

# G - MRC2

```{r}
data <- res_2FF_timecourse$limma_results %>%
  filter(dataset == "treatment effects") %>%
  filter(Gene == "MRC2") %>%
  mutate(contrast = as.numeric(str_remove(contrast, "h"))) %>%
  mutate(n_position = as.numeric(n_position)) %>%
  select(ID, contrast, logFC, ID) %>%
  bind_rows(data.frame(contrast = 0, logFC = 0, ID = "dummy")) %>%
  complete(ID, contrast) %>%
  mutate(
    logFC = ifelse(contrast == 0, 0, logFC)
  ) %>%
  ungroup() %>%
  filter(ID != "dummy") %>%
  separate(ID, into = c("Protein.ID", "Gene", "Modified.Peptide", "Observed.Modifications", "glycan_type", "n_position"), sep = "_", remove = F) %>% 
  mutate(mod = ifelse(glycan_type == "fucosylated", Observed.Modifications, "non-fucosylated")) %>% 
  mutate(n_position = as.numeric(n_position)) 

data$mod %>%  unique


p <- data %>%
  ggplot(aes(group = ID, y = logFC, x = contrast, colour = glycan_type, shape = mod)) +
  geom_hline(yintercept = 0) +
  geom_hline(yintercept = c(log2(1.5), -log2(1.5)), linetype = 3) +
  geom_point(size = 2) +
  geom_smooth(data = data %>% filter(glycan_type != "fucosylated"),method = "lm", formula = y ~ poly(x, 3), size = 0.2, alpha = 0.3, se=F) +
  geom_smooth(data = data %>% filter(glycan_type == "fucosylated"), method = "lm", formula = y ~ poly(x, 3), size = 0.8, se=F) +
  scale_colour_manual(values = pal) +
  scale_shape_manual(values = c("non-fucosylated"  = 1, "HexNAc(2)Hex(5)Fuc(1) % 1362.4808" = 2)) +
  facet_wrap(~n_position, nrow = 1) +
  labs( y = "log2 fold-change 2FF-DMSO", x = "treatment duration [h]", subtitle = "MRC2") +
  cowplot::panel_border() 
plot(p)
```

# H - NRCAM


```{r}
data <- res_2FF_timecourse$limma_results %>%
  filter(dataset == "treatment effects") %>%
  filter(Gene == "NRCAM") %>%
  mutate(contrast = as.numeric(str_remove(contrast, "h"))) %>%
  select(ID, contrast, logFC, ID) %>%
  bind_rows(data.frame(contrast = 0, logFC = 0, ID = "dummy")) %>%
  complete(ID, contrast) %>%
  mutate(
    logFC = ifelse(contrast == 0, 0, logFC)
  ) %>%
  ungroup() %>%
  filter(ID != "dummy") %>%
  separate(ID, into = c("Protein.ID", "Gene", "Modified.Peptide", "Observed.Modifications", "glycan_type", "n_position"), sep = "_", remove = F) %>% 
  mutate(mod = ifelse(glycan_type == "fucosylated", Observed.Modifications, "non-fucosylated")) %>% 
  filter(n_position %in% c(1019, 223, 276, 507, 993)) %>% 
  mutate(n_position = as.numeric(n_position))

data$mod %>%  unique

p <- data %>%
  ggplot(aes(group = ID, y = logFC, x = contrast, colour = glycan_type, shape = mod)) +
  geom_hline(yintercept = 0) +
  geom_hline(yintercept = c(log2(1.5), -log2(1.5)), linetype = 3) +
  geom_point(size = 2) +
  geom_smooth(data = data %>% filter(glycan_type != "fucosylated"),method = "lm", formula = y ~ poly(x, 3), size = 0.2, alpha = 0.3, se=F) +
  geom_smooth(data = data %>% filter(glycan_type == "fucosylated"), method = "lm", formula = y ~ poly(x, 3), size = 0.8, se=F) +
  scale_color_manual(values = pal) +
  scale_shape_manual(values = c("non-fucosylated"  = 1, "HexNAc(2)Hex(5)Fuc(1) % 1362.4808" = 2, "HexNAc(2)Hex(4)Fuc(1) % 1200.4280" = 3, "HexNAc(6)Hex(3)Fuc(2) % 1996.7506" =4, "HexNAc(2)Hex(1)Fuc(1) % 714.2695"=5 )) +
  facet_wrap(~n_position, nrow = 1) +
  labs( y = "log2 fold-change 2FF-DMSO", x = "treatment duration [h]", subtitle = "NRCAM") +
  cowplot::panel_border() 
plot(p)
```

# Supplementary

## A - correlation matrix

```{r}
m <- res_2FF_timecourse$psm_normalised %>%
  mutate(sample = paste(timepoint, condition, replicate, sep = "_")) %>%
  dcast(
    ID ~ sample,
    value.var = "quant", fill = NA
  ) %>%
  drop_na() %>%
  column_to_rownames("ID") %>%
  as.matrix()

m %>%
  cor(method = "spearman") %>%
  ComplexHeatmap::Heatmap(
      col = c("white", "indianred", "darkred"),name = "Spearman\ncorrelation", row_names_side = "right", show_column_dend = F
  )

# check for biological rpelicates of the same condition
m <- res_2FF_timecourse$psm_normalised %>%
  filter(condition == "DMSO" & timepoint == "72h") %>% 
  mutate(sample = paste(timepoint, condition, replicate, sep = "_")) %>%
  dcast(
    ID ~ sample,
    value.var = "quant", fill = NA
  ) %>%
  drop_na() %>%
  column_to_rownames("ID") %>%
  as.matrix()

m %>%
  cor(method = "spearman") %>%  mean()
```

## B - FP PCA

```{r}
pca_plot <- function(data_matrix, x, y, fx, fy, l, u, pal, title) {
  m <- data_matrix
  n_obs <- nrow(m)

  m <- m[matrixStats::rowVars(m, na.rm = T) %>%
    order(decreasing = T) %>%
    head((n_obs / 100) * 10), ]

  pca <- prcomp(t(m))

  data <- pca$x %>%
    as.data.frame() %>%
    rownames_to_column("sample") %>%
    select(sample, x = {{ x }}, y = {{ y }}) %>%
    separate(sample, c("timepoint", "condition", "replicate"), sep = "_", remove = F) %>%
    mutate(timepoint = factor(timepoint, levels = c("0h", "8h", "24h", "48h", "72h")))

  var <- (pca$sdev)^2 / sum(pca$sdev^2) * 100
  vx <- as.numeric(str_extract(as.character({{ x }}), "\\d"))
  vy <- as.numeric(str_extract(as.character({{ y }}), "\\d"))

  p <- data %>%
    ggplot(aes(x = x * fx, y = y * fy, fill = condition, shape = timepoint)) +
    geom_hline(yintercept = 0, colour = "grey", linetype = 3) +
    geom_vline(xintercept = 0, colour = "grey", linetype = 3) +
    geom_point(size = 4, stroke = 0.5, colour = "black") +
    scale_fill_manual(values = pal) +
    scale_shape_manual(values = c(21, 24, 22, 23, 25)) +
    cowplot::panel_border() +
    coord_fixed() +
    lims(x = c(l, u), y = c(l, u)) +
    # guides(fill = "none", shape = "none") +
    labs(
      x = paste0(as.character({{ x }}), " (", round(var[vx], digits = 1), "%)"),
      y = paste0(as.character({{ y }}), " (", round(var[vy], digits = 1), "%)"),
      subtitle = title
    )

  plot(p)
}

m_fp <- res_2FF_timecourse$FP_normalised %>%
  mutate(sample = paste(timepoint, condition, replicate, sep = "_")) %>%
  dcast(
    ID ~ sample,
    value.var = "quant_norm", fill = NA
  ) %>%
  drop_na() %>%
  column_to_rownames("ID") %>%
  as.matrix()

pca_plot(m_fp, "PC1", "PC2", 1, 1, -20, 20, pal = c("grey", "darkcyan"), "FP") 
```

## C - volcanos

```{r}
res_2FF_timecourse$limma_results %>%
  filter(dataset == "treatment effects" & glycan_type %in% c("high mannose", "fucosylated", "sialylated", "complex")) %>%
  ggplot(aes(x = logFC, y = -log10(P.Value), colour = direction)) +
  geom_vline(xintercept = 0) +
  geom_vline(xintercept = c(log2(1 / 1.5), log2(1.5)), linetype = 3) +
  geom_point(alpha = 0.2) +
  scale_colour_manual(values = c("dodgerblue4", "lightgrey", "indianred")) +
  facet_grid(glycan_type ~ contrast) +
  cowplot::theme_cowplot() +
  cowplot::panel_border()+
  labs(x= "log2 fold-change 2FF-DMSO" )
```

## D - site specificty

```{r}
hitfrac_df <- res_2FF_timecourse$limma_results %>%
  filter(dataset == "treatment effects") %>%
  mutate(glycan_type = ifelse(glycan_type == "fucosylated", glycan_type, "other")) %>%
  group_by(Protein.ID, Gene, glycan_type, n_position, hit) %>%
  count() %>%
  dcast(Protein.ID + Gene + glycan_type + n_position ~ hit, fill = 0) %>%
  mutate(sum_forms = hit + `no hit`) %>%
  filter(sum_forms > 3) %>%
  filter(hit > 0) %>%
  group_by(Protein.ID, Gene, glycan_type, n_position) %>%
  summarise(hit_fraction = hit / sum_forms)

hitfrac_df %>%
  filter(hit_fraction > 0) %>%
  ggplot(aes(x = hit_fraction, y = -1.2, colour = glycan_type)) +
  ggforce::geom_sina(orientation = "y", stroke = 0, alpha = 0.5, size = 2.5, pos = position_dodge(1.2)) +
  stat_summary(orientation = "y", geom = "crossbar", colour = "black", fun = mean, aes(group = glycan_type), pos = position_dodge(1.2)) +
  geom_density(aes(x = hit_fraction, colour = glycan_type), inherit.aes = FALSE, size = 0.8, bounds = c(0, 1)) +
  geom_hline(yintercept = 0, colour = "grey30") +
  scale_y_continuous(labels = scales::label_number(accuracy = 1), limits = c(-2, 9)) +
  scale_color_manual(values = c("#377eb8ff", "grey")) +
  labs(x = "fraction of significantly\n regulated glycoforms per site", y = "data | density") 
```










