---
title: "Plots for Figure 1"
output:
  html_document:
    keep_md: yes
    toc: yes
    theme: united
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

# General settings

```{r setup}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  include = TRUE,
  cache = TRUE,
  cache.lazy = FALSE,
  eval = TRUE,
  fig.width = 4 * (1 + sqrt(5)) / 2, 
  fig.height = 4,
  dpi = 700
)
knitr::opts_knit$set(root.dir = "C:/Users/burtsche/Documents/Glycoproteomics/")
```

## Packages

```{r, message=F, warning =F, include=}
library(tidyverse)
library(ggplot2); theme_set(cowplot::theme_cowplot(font_size = 15))
library("reshape2")
library(ggrepel)
library(knitr)
library(Biostrings)
library(ComplexHeatmap)
library(viridis)

mutate <- dplyr::mutate
select <- dplyr::select
group_by <- dplyr::group_by
```

```{r}
options(ggplot2.discrete.colour= c("orange3", "darkslateblue", "darkred", "darkgreen", "darkgrey", "darkviolet"))
options(ggplot2.discrete.fill= c("orange3", "darkslateblue", "darkred", "darkgreen", "darkgrey", "darkviolet"))
```


```{r}
# load("data/top_runs/230227_HEK_HeLa_glyco_3best_runs_largedatabase_psm_processed.RData")
```

# A

workflow diagram

# B

Combine single shot data


```{r}
load("data/processed/2023-05-16_Hela_lf_scanranges_3rep_psm_processed.RData")
load("data/processed/2023-05-16_Mouse_brain_lf_singleshot_psm_processed.RData")
psm_singleshot_combined <- res_singleshot$psm %>% 
  bind_rows(res_scanranges$psm %>%  filter(scan_range == "700-2000")) %>% 
  mutate(replicate = ifelse(is.na(replicate), data, replicate))
```

```{r}
psm_singleshot_combined %>% 
  distinct(species,replicate, Protein.ID, Modified.Peptide, Observed.Modifications)%>% 
  group_by(species, replicate) %>% 
  count(feature = "glyco\npeptides") %>% 
  bind_rows(psm_singleshot_combined %>% 
    distinct(species, replicate, Protein.ID, n_position) %>% 
    group_by(species, replicate)%>% 
    count(feature = "glyco\nsites") ) %>% 
  bind_rows(psm_singleshot_combined %>% 
    distinct(species, replicate, Protein.ID) %>% 
    group_by(species, replicate) %>% 
    count(feature = "glyco\nproteins"))%>% 
  mutate(feature = factor(feature, levels = c("glyco\npeptides", "glyco\nsites", "glyco\nproteins"))) %>% 
    group_by(feature, species) %>% 
  summarise(mean_IDnumber = mean(n), sd = sd(n))%>% 
  # filter(grepl("mouse", species)) %>% 
  ggplot(aes(x = feature, y = mean_IDnumber, fill = species)) +
  geom_bar(stat = "identity", pos = "dodge") +
  geom_text(aes(label = round(mean_IDnumber)), vjust = -1.5, pos = position_dodge(width = 1), size = 3) +
  geom_errorbar(aes(ymin=mean_IDnumber-sd, ymax=mean_IDnumber+sd), width=.2,
                 position=position_dodge(.9))+
  theme(#axis.text.x = element_text(angle = 45, hjust = 1, vjust =1), 
        #legend.position = "none",
        axis.ticks.y = element_blank(), axis.text.y = element_blank()) +
  #lims(y = c(0, 28000)) +
  #facet_wrap(~feature, scales = "free") +
  labs(y = "ID number", x = "")
```

# C

```{r}
#load("data/top_runs/230213_allspecies_psm_processed.RData")
load("data/processed/2023-05-16_humancelllines_lf_3best_psm_processed.RData")
load("data/processed/2023-05-16_mousebrain_fractionated_Nglyco_psm_processed.RData")
```


```{r}
res_species$psm_total %>% 
  # filter(grepl("human", species)) %>% 
  mutate(glycosylation = as.character(glycosylation)) %>%
  # group_by(species, modification, data) %>% 
  # count()%>% 
  mutate(replicate = data) %>% 
  bind_rows(res_singleshot$psm_total) %>% 
  distinct(species, modification, Protein.ID, Modified.Peptide, replicate) %>% 
  group_by(species, modification, replicate) %>% 
  count()%>% 
  dcast(species + replicate ~ modification, value.var = "n")%>% 
  mutate(specificity = (100/(glycosylation + unmodified))*glycosylation) %>% 
  group_by(species) %>% 
  summarise(mean_specificity = mean(specificity), sd = sd(specificity)) %>% 
  ggplot(aes(x = species, y = mean_specificity, fill = species)) +
  geom_bar(stat = "identity", pos = "dodge") +
  geom_errorbar(aes(ymin=mean_specificity-sd, ymax=mean_specificity+sd), width=.2,
                 position=position_dodge(.9)) +
  ylim(c(0,100)) +
  theme(legend.position = "none")  +
  labs(y = "specificity (% PSM)", x = "")
# 
# +
#   labs(title = "Glycoproteomics workflow specificity") 
```

# D

```{r}
load("data/processed/2023-05-16_humancelllines_lf_3best_psm_processed.RData")
load("data/processed/2023-05-16_mousebrain_fractionated_Nglyco_psm_processed.RData")
```

```{r}
# identification nn
res_species$psm %>% 
  distinct(species, Protein.ID, Modified.Peptide, Observed.Modifications) %>% 
  group_by(species) %>% 
  count(feature = "glyco\npeptides") %>% 
  bind_rows(res_species$psm %>% 
    distinct(species, Protein.ID, n_position) %>% 
    group_by(species)%>% 
    count(feature = "glyco\nsites") ) %>% 
  bind_rows(res_species$psm %>% 
    distinct(species, Protein.ID) %>% 
    group_by(species) %>% 
    count(feature = "glyco\nproteins"))%>% 
  mutate(feature = factor(feature, levels = c("glyco\npeptides", "glyco\nsites", "glyco\nproteins")))%>% 
  filter(grepl("mouse", species)) %>% 
  ggplot(aes(x = feature, y = n, fill = species)) +
  geom_bar(stat = "identity", n_position = "dodge") +
  geom_text(aes(label = n), vjust = -0.5) +
  lims(y = c(0, 170000)) +
  theme(
        legend.position = "none",
        axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
  #facet_wrap(~feature, scales = "free") +
  labs(y = "ID number \n deep fractionation", x = "")
```

```{r}
load("data/processed/2023-05-16_mousebrain_fractionated_Oglyco_psm_processed.RData")
```

```{r}
res_Oglyco$summary %>% 
  melt() %>% 
  mutate(variable = ifelse(variable == "n_glycoproteins", "glyco\nproteins", "glyco\npeptides")) %>% 
  ggplot(aes(x = variable, y = value)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = value), size = 3, vjust = -0.5 ) +
  #theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
  labs(y = "ID number \n deep fractionation O-glyco", x= "")
res_Oglyco$summary %>% 
  melt()
```


# E

```{r}
load("data/processed/2023-05-16_mousebrain_fractionated_Nglyco_psm_processed.RData")
load("data/comparison_to_datasets/uniprot_annotation_comparison.RData")
```

```{r}
ggplot(uniprot_anno_comparison %>% 
           filter(evidence != "combined" & evidence != "similarity") %>% 
            distinct(evidence, Protein.ID, n_position) %>%
           group_by(evidence) %>%
           summarise(n= n()),
         aes(x= "mouse brain", y= n, fill = evidence)) +
    geom_bar(stat = "identity",pos = "stack") + # position = position_stack(reverse = TRUE)) +
    # scale_fill_manual(values = c("peru", "wheat3", "grey70","turquoise4")) +
    scale_fill_manual(values = c("peru", "wheat3", "turquoise4")) +
    labs(x= "", y = "# of glycosites")
```

# F

```{r}
load("data/enrichments/2023-05-16_ER_string_NvsO.RData")
```

```{r}
ER_NvsO_string %>% 
  ungroup() %>% 
  filter(grepl("^Intracellular organelle$|^Plasma membrane$", description) & category == "Component") %>% 
  #mutate(cc = ifelse(grepl("^membrane$|^integral component of membrane$|^plasma membrane$", Term), "membrane", "cytoplasm")) %>% 
  ggplot(aes(x = -log10(fdr), y = description, colour = dataset)) +
  geom_vline(xintercept = -log10(0.05), linetype = 3) +
  geom_point(aes(size = number_of_genes)) +
  scale_size(range = c(3, 10)) +
  labs(y = "", x = "-log10 false discovery rate")+
  theme(panel.grid.major.y = element_line(colour = "grey60"), legend.position = "right") 
```


# G

```{r}
load("data/comparison_to_datsets/2023-05-16_massrange_comparison.RData")
```

```{r}
massrange_comparison %>% 
  filter(is.finite(mass) & mass > 0) %>% 
  ggplot(aes(x = mass, fill = dataset, colour = dataset)) +
  geom_histogram( position="dodge", binwidth = 500) +
  scale_colour_manual(values = c("springgreen4", "darkorange", 'purple4'))+
  scale_fill_manual(values = c("springgreen4", "darkorange", 'purple4' )) +
  labs(y = "ID number", x = "glycan mass")

```

