---
title: "surfac acc figure"
output:
  html_document:
    keep_md: yes
    toc: yes
    theme: united
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

# General settings

```{r setup}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  include = TRUE,
  cache = TRUE,
  cache.lazy = FALSE,
  eval = TRUE,
  fig.width = 4 * (1 + sqrt(5)) / 2, 
  fig.height = 4,
  dpi = 700
)
knitr::opts_knit$set(root.dir = "/Users/burtsche/Documents/01_repos/Glycoproteomics/")
```

```{r}
 setwd("/Users/burtsche/Documents/01_repos/Glycoproteomics/")
```


## Packages

```{r, message=F, warning =F}
library(tidyverse)
library(ggplot2);theme_set(cowplot::theme_cowplot(font_size = 15))
library("reshape2")
library(ggrepel)
library(ggpubr)

mutate <- dplyr::mutate
select <- dplyr::select
group_by <- dplyr::group_by
filter <- dplyr::filter
```

```{r}
options(ggplot2.discrete.colour= c("darkorange", "darkblue", "darkgreen", "darkred"),
        ggplot2.discrete.fill= c("darkorange", "darkblue", "darkgreen", "darkred"))

tilted <-  theme(axis.text.x = element_text(angle = 45, hjust =1, vjust = 1))
blank <- theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())

order <- c("sialylated", "fucosylated", "high mannose", "complex/hybrid", "phospho", "paucimannose", "small")
pal <- c("lightgrey", "#E41A1C", "#377EB8", "#4DAF4A","#984EA3" ,"#FF7F00", "#FFFF33", "#A65628", "mediumseagreen", "grey")
names(pal) <- c("FP", "sialylated", "fucosylated", "high mannose", "complex/hybrid", "phospho", "paucimannose", "small", "hit", "no hit")

```

# Load

```{r}
load("results/2024-01-09_res_hek_pngase_glyco.RData")
load("results/2024-01-09_res_hek_proteinasek_glyco.RData")
```

# Functions

```{r}
#source("~/Documents/generic_functions.R")
```

# Combine data

```{r}
res_surface_acc <- list()

res_surface_acc$limma_results <- tt <- bind_rows(
  res_hek_pngase_glyco$limma_results%>% 
    mutate(siteID = paste0(Protein.ID, "_", n_position)) %>%
    filter(siteID %in% res_hek_pngase_glyco$more_than_1change$siteID),
  res_hek_proteinasek_glyco$limma_results%>% 
    mutate(siteID = paste0(Protein.ID, "_", n_position)) %>%
    filter(siteID %in% res_hek_proteinasek_glyco$more_than_1change$siteID)
) %>% 
  distinct(ID, dataset, .keep_all = T) %>% 
  mutate(glycan_type = ifelse(glycan_type == "extra high mannose", "high mannose", glycan_type))

res_surface_acc$limma_results_complete <- tt <- bind_rows(
  res_hek_pngase_glyco$limma_results,
  res_hek_proteinasek_glyco$limma_results
) %>% 
  distinct(ID, dataset, .keep_all = T) %>% 
  mutate(glycan_type = ifelse(glycan_type == "extra high mannose", "high mannose", glycan_type)) %>% 
  mutate(siteID = paste0(Protein.ID, "_", n_position)) 


res_surface_acc$psm <- tt <- bind_rows(
  "pngase" = res_hek_pngase_glyco$glyco_psm_normalised,
  "proteinasek" = res_hek_proteinasek_glyco$glyco_psm_normalised,.id = "dataset"
)

save(res_surface_acc, file = paste0("data/paper/revision1/processed/",Sys.Date(),"_res_surface_acc.RData"))
```

## numbers

```{r}
res_surface_acc$limma_results_complete %>% 
     group_by(hit) %>% 
     summarise(peptides = n_distinct(ID), sites = n_distinct(siteID), prots = n_distinct(Protein.ID)) %>% 
  filter(hit == "hit")

res_surface_acc$limma_results %>% 
     group_by(hit) %>% 
     summarise(peptides = n_distinct(ID), sites = n_distinct(siteID), prots = n_distinct(Protein.ID)) %>% 
  filter(hit == "hit")

res_surface_acc$limma_results %>% 
  drop_na() %>% 
     group_by(dataset, hit) %>% 
     summarise(sites = n_distinct(siteID), prots = n_distinct(Protein.ID))

res_surface_acc$limma_results %>% 
     distinct(ID) %>%  nrow()
```


# A - workflow

# B - barplot

```{r}
locations_of_interest <- c("Golgi apparatus", "Plasma membrane", "Endoplasmic reticulum", "Lysosome", "Cytoplasm", "Extracellular")

compartment_anno <- tt <- read_tsv("data/combined_loc_df.tsv")%>%
  mutate(description = ifelse(grepl("Extracellular", description), "Extracellular", description)) %>% 
  filter(description %in% locations_of_interest) %>% 
  group_by(gene) %>%
  filter(score > 2.5) %>%
  mutate(species = ifelse(grepl("MUS", ensembl_prot), "mus musculus", "homo sapiens")) %>% 
  mutate(Gene = gene) %>% 
  select(-gene) %>% 
  group_by(Gene) %>% 
  mutate(n_annos =n()) 

pm_proteins <- compartment_anno %>% 
  filter(description == "Plasma membrane")

extracell_proteins <- compartment_anno %>% 
  filter(description == "Extracellular")

compartment_anno <- compartment_anno %>% 
  mutate(description = ifelse(Gene %in% extracell_proteins$Gene, "Extracellular", description)) %>% 
  mutate(description = ifelse(Gene %in% pm_proteins$Gene, "Plasma membrane", description)) %>% 
  distinct(species, Gene, description)


res_surface_acc$limma_results %>%
  filter(hit == "hit" & logFC > 0) %>% 
  inner_join(compartment_anno %>%  distinct(Gene, description), by = "Gene") %>% 
  distinct(Protein.ID, Gene, ID, description, dataset) %>% 
  ggplot(aes(x = description, fill =dataset)) +
  geom_bar(pos = "dodge") +
  tilted



```

# C - example1

```{r}
res_surface_acc$limma_results_complete %>%
      filter(Gene == "SLC39A6") %>% 
      arrange(glycan_type) %>%
      ungroup() %>%
      # mutate(text_label = as.character(gsub(" %.+$", "", Observed.Modifications))) %>%
      select(glycan_type, logFC, n_position, hit, dataset, Observed.Modifications) %>%
      mutate(glycan_type = ifelse(grepl("extra", glycan_type), "high mannose", glycan_type)) %>%
      ggplot(
        aes(
          x = glycan_type,
          y = logFC,
          colour = glycan_type,
          shape = hit, 
          label = Observed.Modifications
        )
      ) +
      geom_hline(yintercept = 0, linetype = 1) +
      geom_hline(yintercept = 0.6, linetype = 3) +
  ggbeeswarm::geom_beeswarm(cex = 3) +
      #geom_jitter(width = 0.2) +
      # geom_point(position = position_dodge(width = 0.5), size = 2) +
      # ggrepel::geom_text_repel(aes(label = text_label),colour = "black", size = 1.5) +
      scale_color_manual(values = pal) +
      # scale_alpha_manual(values = c("hit"=1, "no hit" = 1)) +
      #theme_bw(base_size = 14) +
      theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
      facet_grid(dataset ~ n_position) +
  panel_border() +
      labs(y = "log2 fold-change total-enzyme")
```

# D - example2

```{r}
res_surface_acc$limma_results_complete %>%
      filter(Gene == "DSC2") %>% 
      arrange(glycan_type) %>%
      ungroup() %>%
      # mutate(text_label = as.character(gsub(" %.+$", "", Observed.Modifications))) %>%
      select(glycan_type, logFC, n_position, hit, dataset, Observed.Modifications) %>%
      mutate(glycan_type = ifelse(grepl("extra", glycan_type), "high mannose", glycan_type)) %>%
      ggplot(
        aes(
          x = glycan_type,
          y = logFC,
          colour = glycan_type,
          shape = hit, 
          label = Observed.Modifications
        )
      ) +
      geom_hline(yintercept = 0, linetype = 1) +
      geom_hline(yintercept = 0.6, linetype = 3) +
  ggbeeswarm::geom_beeswarm(cex = 3) +
      #geom_jitter(width = 0.2) +
      # geom_point(position = position_dodge(width = 0.5), size = 2) +
      # ggrepel::geom_text_repel(aes(label = text_label),colour = "black", size = 1.5) +
      scale_color_manual(values = pal) +
      # scale_alpha_manual(values = c("hit"=1, "no hit" = 1)) +
      #theme_bw(base_size = 14) +
      theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
      facet_grid(dataset ~ n_position) +
  panel_border() +
      labs(y = "log2 fold-change total-enzyme")
```


# E - violin

```{r}
res_surface_acc$limma_results %>% 
  filter(glycan_type %in% c("complex/hybrid", "fucosylated", "high mannose", "sialylated")) %>% 
  inner_join(compartment_anno %>%  distinct(Gene, description), by = "Gene") %>% 
  filter(description == "Plasma membrane") %>% 
  ggplot(aes(x = glycan_type, colour =glycan_type, y = logFC)) +
  geom_hline(yintercept = 0) +
  ggforce::geom_sina() +
  stat_summary(aes(group = description),fun = median, geom = "crossbar",
               position = position_dodge(0.9), colour = "black") +
  ggpubr::stat_compare_means(ref.group = "high mannose", label = "p.signif", method = "t.test") +
  facet_wrap(~dataset, nrow = 1) +
  tilted +
  scale_colour_manual(values = pal) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
  labs(y = "log2 fold-change control-enzyme")
```

# F - correlation singel

```{r}
res_surface_acc$limma_results %>% 
  dcast(ID ~ dataset, value.var = "logFC", fill = NA) %>% 
  drop_na() %>% 
  ggplot(aes(x = PNGase_comp, y = ProteinaseK_comp)) +
  geom_hline(yintercept = 0, linetype =3)+
  geom_vline(xintercept = 0, linetype =3) +
  geom_abline(slope=1, linetype =3)+
  geom_point(size =2, stroke =NA, alpha=0.5, colour = "darkblue")+
  #geom_smooth(method = "lm") +
  stat_cor() +
  lims(x = c(-1,3), y = c(-1,3)) +
  coord_fixed(ratio= 1) +
  labs(x = "logFC pngase", y = "logFC proteinasek")
```

# G - scatterplot hit frac

```{r}
hit_fractions <- res_surface_acc$limma_results %>% 
  group_by(dataset, Observed.Modifications, hit) %>% 
  count() %>% 
  group_by(dataset, Observed.Modifications) %>% 
  mutate(total = sum(n)) %>% 
  ungroup() %>% 
  mutate(frac = n/total) %>% 
  filter(hit == "hit") %>% 
  distinct(dataset, Observed.Modifications, frac) %>% 
  group_by(Observed.Modifications) %>% 
  summarise(frac= mean(frac))

res_surface_acc$limma_results %>% 
  filter(hit == "hit") %>% 
  group_by(dataset, Observed.Modifications, glycan_type) %>% 
  summarise(n_hits = n()) %>% 
  left_join(hit_fractions) %>% 
  dcast(Observed.Modifications +glycan_type+frac ~ dataset, value.var ="n_hits", fill = 0) %>% 
  mutate(Observed.Modifications = str_remove(Observed.Modifications, "\\%.+$")) %>% 
  ggplot(aes(x = PNGase_comp, y = ProteinaseK_comp, colour = glycan_type, size = frac)) +
  geom_point(alpha = 0.5) +
  ggrepel::geom_text_repel(aes(label =Observed.Modifications), size = 2, max.overlaps = 20) +
  scale_colour_manual(values = pal) +
  coord_fixed(ratio= 1) +
  lims(x=c(0, 80), y=c(0, 80)) 
  #labs(title = "number of hits per comp per dataset")
```

# Supplements (Figure S6)

## A - corr matrix

```{r}
res_surface_acc$psm  %>%  
  filter(grepl("ctl", treatment) & grepl("protein", dataset)) %>% 
  acast(ID ~ treatment + replicate + dataset,value.var = "quant", fun.aggregate = median, fill = 0) %>% 
  cor(use = "pairwise.complete.obs", method = "spearman") %>% 
  ComplexHeatmap::Heatmap(name = "corr",col = circlize::colorRamp2(c(0.95,1), c( "white", "darkred")))

res_surface_acc$psm  %>%  
  filter(grepl("ctl", treatment) & grepl("protein", dataset)) %>% 
  cor(use = "pairwise.complete.obs", method = "spearman") %>%  mean()
```


## B - volcanos

```{r}
ggplot(
  res_surface_acc$limma_results,
  aes(x = logFC, y = -log10(P.Value), colour = direction)
) +
  geom_hline(yintercept = -log10(0.05), linetype =3)+
  geom_vline(xintercept = 0, linetype =3)+
  geom_point(alpha = 0.5, stroke = 0) +
  #geom_text_repel(aes(label = Gene), size =2) +
  scale_colour_manual(values = c("dodgerblue4", "lightgrey", "indianred")) +
  facet_wrap( ~ dataset) +
  # theme_bw(14) +
  theme(panel.grid = element_blank()) +
  cowplot::panel_border() +
  labs(x = "log2 fold-change\ntotal-enzyme", y = "-log10 p-value")
```

## C - Martin

## D - top comps

```{r}
top_ids <- res_surface_acc$limma_results %>% 
  filter(glycan_type %in% c("complex/hybrid", "fucosylated", "sialylated")) %>% 
  group_by(dataset, Observed.Modifications) %>% 
  summarise(n = n()) %>% 
  group_by(dataset) %>% 
  slice_max(order_by = n, n = 10) %>% 
  arrange(n)

p1 <- res_surface_acc$limma_results %>% 
  filter(Observed.Modifications %in% top_ids$Observed.Modifications) %>% 
  group_by(dataset, Observed.Modifications, hit) %>% 
  summarise(n = n()) %>% 
  mutate(hit = factor(hit, levels = c("no hit", "hit"))) %>% 
  filter(dataset == "PNGase_comp") %>% 
  group_by(Observed.Modifications) %>% 
  mutate(total = sum(n)) %>% 
   ungroup() %>% 
   mutate(frac = n/total) %>% 
   mutate(frac= ifelse(hit == "hit", n, 0)) %>% 
   mutate(Observed.Modifications = str_remove(Observed.Modifications, "\\%.+$")) %>% 
  ggplot(aes(x = reorder(Observed.Modifications, frac), y= n, fill = hit)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = pal) +
  coord_flip() +
  facet_wrap(~dataset) +
  labs(x = "", y = "# IDs") +
  theme(legend.position = "none")
 
p2 <- res_surface_acc$limma_results %>% 
  filter(Observed.Modifications %in% top_ids$Observed.Modifications) %>% 
  group_by(dataset, Observed.Modifications, hit) %>% 
  summarise(n = n()) %>% 
  mutate(hit = factor(hit, levels = c("no hit", "hit"))) %>% 
  filter(dataset == "ProteinaseK_comp") %>% 
  group_by(Observed.Modifications) %>% 
  mutate(total = sum(n)) %>% 
   ungroup() %>% 
   mutate(frac = n/total) %>% 
   mutate(frac= ifelse(hit == "hit", n, 0)) %>% 
     mutate(Observed.Modifications = str_remove(Observed.Modifications, "\\%.+$")) %>% 
  ggplot(aes(x = reorder(Observed.Modifications, frac), y= n, fill = hit)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = pal) +
  coord_flip() +
  labs(y = "# IDs", x = "") +
  facet_wrap(~dataset)+
  theme(legend.position = "none")

 plot_grid(p1, p2, ncol = 2, align = 'hv')
```

## E - mass

```{r}
res_surface_acc$limma_results%>% 
  mutate(mass = as.numeric(str_extract(Observed.Modifications, "\\d+\\.\\d+$")),
         anno = ifelse(hit == "hit", dataset, "no hit")) %>% 
  ggplot(aes(x = mass, colour = anno)) +
  geom_density(size = 1) +
scale_colour_manual(values = c("grey", "darkorange", "darkblue"))
```

## F - fuc/sia bars

```{r}
p1 <- res_surface_acc$limma_results %>%
  mutate(
    fuc_cat = str_extract_all(Observed.Modifications, "Fuc\\(\\d+\\)"),
    sia_cat = str_extract_all(Observed.Modifications, "NeuGc\\(\\d+\\)|NeuAc\\(\\d+\\)")
  ) %>%
  mutate(
    fuc_cat = sapply(
      str_extract_all(fuc_cat, "[[:digit:]]+"),
      function(x) ifelse(identical(x, character(0)), NA, sum(as.numeric(x)))
    ),
    sia_cat = sapply(
      str_extract_all(sia_cat, "[[:digit:]]+"),
      function(x) ifelse(identical(x, character(0)), NA, sum(as.numeric(x)))
    )
  ) %>%
  filter(sia_cat > 0) %>% 
  mutate(n_sia_sugars = as.factor(sia_cat)) %>% 
  ggplot(aes(x = hit, fill = n_sia_sugars)) +
  geom_bar(pos = "fill") +
  scale_fill_brewer(palette = "Reds") +
  facet_wrap(~dataset) +
  tilted +
  labs(y = "fraction")

p2 <- res_surface_acc$limma_results %>%
  mutate(
    fuc_cat = str_extract_all(Observed.Modifications, "Fuc\\(\\d+\\)"),
    sia_cat = str_extract_all(Observed.Modifications, "NeuGc\\(\\d+\\)|NeuAc\\(\\d+\\)")
  ) %>%
  mutate(
    fuc_cat = sapply(
      str_extract_all(fuc_cat, "[[:digit:]]+"),
      function(x) ifelse(identical(x, character(0)), NA, sum(as.numeric(x)))
    ),
    sia_cat = sapply(
      str_extract_all(sia_cat, "[[:digit:]]+"),
      function(x) ifelse(identical(x, character(0)), NA, sum(as.numeric(x)))
    )
  ) %>%
  mutate(
    classification = ifelse((hit == "hit" & abs(logFC) < 1.2), "0.6-1.2", hit),
    classification = ifelse((hit == "hit" & abs(logFC) > 1.2), ">1.2", classification)
  ) %>% 
  mutate(fc_cat = ifelse((hit == "hit" &  logFC > 1.2), ">1.2", "0.6-1.2")) %>% 
  mutate(fc_cat = ifelse(hit == "no hit", "no hit", fc_cat)) %>% 
  filter(fuc_cat > 0) %>% 
  mutate(n_fuc_sugars = as.factor(fuc_cat)) %>% 
  ggplot(aes(x = hit, fill =n_fuc_sugars)) +
  geom_bar(pos = "fill") +
  scale_fill_brewer(palette = "Reds") +
  facet_wrap(~dataset) +
  tilted +
  labs(y = "fraction")

 plot_grid(p1, p2, ncol = 2, align = 'hv')
```

## G - venn

```{r}

input2 <- res_surface_acc$limma_results  %>% 
  #ungroup()%>%  
  drop_na() %>% 
  filter(hit == "hit") %>% 
  distinct(dataset, siteID) %>% 
  drop_na()

x <- split(input2 , input2$dataset)
x <- list("PNGase" = x$PNGase_comp$siteID, "ProteinaseK" = x$ProteinaseK_comp$siteID)

v <- nVennR::plotVenn(x, setColors = c("darkorange", "darkblue"), opacity=0.2, borderWidth=4,  fontScale = 2, labelRegions = F)
```

## H - complete scatter

```{r}
tt <- res_surface_acc$limma_results_complete %>% 
  mutate(annotation = ifelse(siteID %in% res_hek_pngase_glyco$more_than_1change$siteID &siteID %in% res_hek_proteinasek_glyco$more_than_1change$siteID, "both", "not affected")) %>% 
  mutate(annotation = ifelse(siteID %in% res_hek_proteinasek_glyco$more_than_1change$siteID & annotation != "both", "proteinase",annotation )) %>% 
  mutate(annotation = ifelse(siteID %in% res_hek_pngase_glyco$more_than_1change$siteID & annotation != "both", "pngase",annotation )) %>% 
  distinct(siteID, annotation)

res_surface_acc$limma_results_complete %>% 
  dcast(ID + siteID ~ dataset, value.var = "logFC", fill = NaN) %>% 
  full_join(tt %>% distinct(siteID, annotation))%>% 
  filter(annotation != "not affected") %>% 
  ggplot(aes(x = PNGase_comp, y = ProteinaseK_comp, colour = annotation)) +
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0) +
  geom_abline(slope=1)+
  geom_point(size =0.5)+
  #geom_smooth(method = "lm") +
  stat_cor()+
scale_colour_manual(values = c("grey", "darkorange", "darkblue")) +
  lims(x = c(-1,3), y = c(-1,3)) +
  coord_fixed(ratio= 1) +
  labs(x = "logFC pngase", y = "logFC proteinasek")
```

## I - Martin


