---
title: "Enrichment analyses"
output:
  html_document:
    keep_md: yes
    toc: yes
    theme: united
    code_folding: hide
editor_options: 
  chunk_output_type: inline
---

# General settings

```{r setup}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  include = TRUE,
  cache = TRUE,
  cache.lazy = FALSE,
  eval = TRUE,
  fig.width = 4 * (1 + sqrt(5)) / 2, 
  fig.height = 4,
  dpi = 700
)
knitr::opts_knit$set(root.dir =  "~/Documents/Glycoproteomics/")
```

## Packages

```{r, message=F, warning =F}
library(tidyverse)
library(ggplot2); theme_set(cowplot::theme_cowplot(font_size = 15))
library("reshape2")
library(ggrepel)
library(knitr)
library(STRINGdb)
library(biomaRt)

mutate <- dplyr::mutate
select <- dplyr::select
group_by <- dplyr::group_by

```

```{r}
options(ggplot2.discrete.colour= c("orange3", "darkslateblue", "darkred", "darkgreen", "darkgrey", "darkviolet"))
options(ggplot2.discrete.fill= c("orange3", "darkslateblue", "darkred", "darkgreen", "darkgrey", "darkviolet"))
```

# Data

```{r}
load("data/paper/processed/2023-05-16_mousebrain_fractionated_Nglyco_psm_processed.RData")
load("data/paper/processed/2023-05-16_mousebrain_fractionated_Oglyco_psm_processed.RData")
```


# Stringdb enrichments

```{r}
string_db <- STRINGdb$new( version="11.5", species=10090,
                           score_threshold=200, network_type="full", input_directory="")
```

## N-glyco: per glycan type

```{r}
ER_string_glycantype <- res_mousebrain_fractionated_Nglyco$psm %>%
  distinct(glycan_type, Gene) %>%
  group_by(glycan_type) %>%
  nest(Gene) %>%
  mutate(ER = map(data, function(df) {
    ER = string_db$get_enrichment(df$Gene)
  })) %>%
  select(-data) %>%
  unnest()

interesting_pathways <- data.frame(
  description = c(
    "Cell adhesion", "Cell migration", "Organelle", "Response to stimulus",
    "Plasma membrane", "Transmembrane signaling receptor activity",
    "Extracellular region", "Signaling", "Axon", "Nervous system development"
  )
)
order <- c("sialylated", "fucosylated", "high mannose", "complex/hybrid", "phospho", "paucimannose", "small")

ER_string_glycantype %>%
  inner_join(interesting_pathways) %>%
  filter(category != "RCTM") %>%
  mutate(glycan_type = factor(glycan_type, levels = order)) %>%
  ggplot(aes(x = glycan_type, y = description, colour = -log10(fdr), size = number_of_genes)) +
  geom_point() +
  scale_colour_viridis_c(option = "rocket", direction = -1, begin = 0.4, end = 0.8) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
  labs(x = "", y = "")

save(ER_string_glycantype, file = paste0("data/paper/enrichments/", Sys.Date(),"_ER_string_N_glycantype.RData"))
```

## N-glyco: microheterogeneity

```{r}
ER_string_microheterogeneity <- res_mousebrain_fractionated_Nglyco$psm %>%
  distinct(Gene, Protein.ID, n_position, Observed.Modifications) %>%
  group_by(Gene, Protein.ID, n_position) %>%
  summarise(n_forms_sites = n_distinct(Observed.Modifications)) %>%
  ungroup() %>%
  mutate(bin = as.character(cut_number(n_forms_sites, n = 3))) %>%
  mutate(bin = factor(bin, levels = c("[1,2]", "(2,11]", "(11,759]"))) %>%
  ungroup() %>%
  distinct(bin, Gene) %>%
  group_by(bin) %>%
  nest(Gene) %>%
  mutate(ER = map(data, function(df) {
    ER = string_db$get_enrichment(df$Gene)
  })) %>%
  select(-data) %>%
  unnest()

interesting_pathways <- data.frame(
  category = c("Process", "Process", "COMPARTMENTS", "COMPARTMENTS", "Function", "Component", "COMPARTMENTS"),
  description = c("Cell adhesion", "Cell-cell adhesion", "Plasma membrane", "Receptor complex", "Transmembrane signaling receptor activity", "Extracellular region", "Cell surface")
)

interesting_pathways <- data.frame(category = c("Process", "COMPARTMENTS",  "Function", "Component"),
           description = c("Cell adhesion","Plasma membrane", "Transmembrane signaling receptor activity", "Extracellular region"))

ER_string_microheterogeneity %>% 
  inner_join(interesting_pathways) %>% 
  ggplot(aes(x = -log10(fdr), y = description, colour = bin)) +
  geom_vline(xintercept = -log10(0.05), linetype = 3) +
  geom_point(aes(size = number_of_genes)) +
  scale_size(range = c(3, 8)) +
  labs(y = "", x = "-log10 false discovery rate")+
  theme(panel.grid.major.y = element_line(colour = "grey60"), legend.position = "right") 

save(ER_string_microheterogeneity, file = paste0("data/paper/enrichments/", Sys.Date(),"_microheterogeneityER_string.RData"))
```

## N-glyco: Uniprot annotation

```{r}
load("data/paper/comparison_to_datasets/uniprot_annotation_comparison.RData")
```


```{r}
ER_notanno_mM <- uniprot_anno_comparison %>%
  mutate(evidence = ifelse(evidence == "not annotated","not annotated" , "annotated")) %>% 
  distinct(evidence, Gene) %>%
  nest(Gene) %>%
  mutate(ER = map(data, function(df) {
    ER = string_db$get_enrichment(df$Gene)
  })) %>%
  select(-data) %>%
  unnest()

interesting_pathways <- data.frame(
  description = c(
    "Cell adhesion",  "Organelle", 
    "Plasma membrane",
    "Extracellular region", "Signaling", "Intracellular"
  )
)
order <- c("sialylated", "fucosylated", "high mannose", "complex/hybrid", "phospho", "paucimannose", "small")

ER_notanno_mM %>%
  inner_join(interesting_pathways) %>%
  filter(category %in% c("Component", "Function", "Process")) %>%
  #mutate(glycan_type = factor(glycan_type, levels = order)) %>%
  ggplot(aes(x = -log10(fdr), y = description, colour = evidence, size = number_of_genes)) +
  geom_vline(xintercept = -log10(0.05), linetype = 3) +
  geom_point() +
  #scale_colour_viridis_c(option = "rocket", direction = -1, begin = 0.4, end = 0.8) +
  theme(panel.grid.major.y = element_line(colour = "grey")) +
  labs( y = "", x = "-log10 false-discovery rate")

save(ER_notanno_mM, file = paste0("data/paper/enrichments/", Sys.Date(),"_uniprotannotationER_string.RData"))
```


## O-glyco: n_glycoforms

```{r}
ER_string_O_microhet <- res_mousebrain_fractionated_Oglyco$psm  %>%
  distinct(Gene, Peptide, Observed.Modifications) %>%
  group_by(Gene) %>%
  summarise(n_gforms = n_distinct(Peptide, Observed.Modifications)) %>%
  mutate(
    n_glycoforms = ifelse(n_gforms == 1, "only one glycoform", "1-5 glycoforms"),
    n_glycoforms = ifelse(n_gforms > 1, "more than one glycoform", n_glycoforms)
  ) %>%
  drop_na() %>%
  distinct(Gene, n_glycoforms) %>%
  group_by(n_glycoforms) %>%
  nest(Gene) %>%
  mutate(ER = map(data, function(df) {
    ER = string_db$get_enrichment(df$Gene)
  })) %>%
  select(-data) %>%
  unnest()

ER_string_O_microhet %>%
  filter(category %in% c("Component", "Function", "Process")) %>% 
  filter(description %in% c("Organelle", "Cell junction", "Plasma membrane", "Regulation of signaling", "Cell adhesion")) %>% 
  ggplot(aes(x = -log10(fdr), y = reorder(description, -number_of_genes), colour = n_glycoforms, size = number_of_genes)) +
  geom_point() +
  geom_vline(xintercept = -log10(0.05), linetype = 3) +
  theme(panel.grid.major.y = element_line(colour = "lightgrey")) +
  labs(y= "")

save(ER_string_O_microhet, file = paste0("data/paper/enrichments/", Sys.Date(),"_microheterogeneityER_string_Oglyco.RData"))
```

## N vs O

```{r}
ER_NvsO_string <- res_mousebrain_fractionated_Nglyco$psm  %>%
  distinct(Gene) %>%
  mutate(dataset = "N-glyco") %>%
  bind_rows(res_mousebrain_fractionated_Oglyco$psm  %>%
    distinct(Gene) %>%
    mutate(dataset = "O-glyco")) %>%
  group_by(Gene) %>%
  mutate(n = n()) %>%
  ungroup() %>%
  mutate(dataset = ifelse(n == 2, "N- and O-glyco", dataset)) %>%
  as.data.frame() %>%
  group_by(dataset) %>%
  nest(Gene) %>%
  mutate(ER = map(data, function(df) {
    ER = string_db$get_enrichment(df$Gene)
  })) %>%
  select(-data) %>%
  unnest()

ER_NvsO_string %>% 
  ungroup() %>% 
  filter(grepl("^Intracellular organelle$|^Plasma membrane$", description) & category == "Component") %>% 
  ggplot(aes(x = -log10(fdr), y = description, colour = dataset)) +
  geom_vline(xintercept = -log10(0.05), linetype = 3) +
  geom_point(aes(size = number_of_genes)) +
  scale_size(range = c(3, 10)) +
  labs(y = "", x = "-log10 false discovery rate")+
  theme(panel.grid.major.y = element_line(colour = "grey60"), legend.position = "right")

save(ER_NvsO_string, file = paste0("data/paper/enrichments/", Sys.Date(),"_ER_string_NvsO.RData"))
```

# Domains

If this doesn't run the first time (server unresponsive), just try again.

```{r}
ensembl <- useEnsembl(biomart = "genes", dataset = "mmusculus_gene_ensembl")

ipro = getBM(attributes=c("uniprot_gn_id", "interpro","interpro_description","interpro_short_description", "interpro_start", "interpro_end"), 
             filters = "uniprot_gn_id",
             values= unique(c(res_mousebrain_fractionated_Nglyco$psm $Protein.ID, res_mousebrain_fractionated_Oglyco$psm$Protein.ID)), 
             mart=ensembl)
```


## N-glyco


```{r}
domain_enrichment_N <- res_mousebrain_fractionated_Nglyco$psm  %>%
  distinct(Protein.ID, Gene, Modified.Peptide, Observed.Modifications, glycan_type, mass, n_position) %>%
  inner_join(ipro, by = c("Protein.ID" = "uniprot_gn_id"), multiple = "all") %>%
  mutate(in_domain = ifelse(n_position > interpro_start & n_position < interpro_end, TRUE, FALSE)) %>%
  filter(!is.na(interpro_description) & !is.na(interpro_start)) %>%
  select(Protein.ID, Modified.Peptide, glycan_type, interpro_description, in_domain) %>%
  filter(in_domain == T) %>%
  mutate(siteID = paste0(Protein.ID, "_", Modified.Peptide)) %>%
  mutate(n_sites = length(unique(siteID))) %>%
  group_by(glycan_type) %>%
  mutate(n_glycan = length(unique(siteID))) %>%
  group_by(interpro_description) %>%
  mutate(n_domain = length(unique(siteID))) %>%
  group_by(glycan_type, interpro_description) %>%
  mutate(n_type_domain = length(unique(siteID))) %>%
  ungroup() %>%
  distinct(glycan_type, interpro_description, n_sites, n_glycan, n_domain, n_type_domain) %>%
  rowwise() %>%
  mutate(
    FT = fisher.test(x = matrix(c(
      n_type_domain,
      n_glycan - n_type_domain,
      n_domain - n_type_domain,
      n_sites - n_glycan - n_domain + n_type_domain
    ), nrow = 2, byrow = T))$p.value,
    odds_ratio = fisher.test(x = matrix(c(
      n_type_domain,
      n_glycan - n_type_domain,
      n_domain - n_type_domain,
      n_sites - n_glycan - n_domain + n_type_domain
    ), nrow = 2, byrow = T))$estimate
  ) %>%
  mutate(
    adj.p.val = p.adjust(FT, method = "BH"),
    hit = ifelse(adj.p.val < 0.05, "hit (adj.p < 0.05)", "no hit (adj.p > 0.05)")
  )

mycolors <- c( 
  '#ff8f42',
"#ba48b6",
'#a80064',
'#805700',
"#018223",
'#0168b9',
"#01e8a8"
)

domain_enrichment_N %>% 
  filter(adj.p.val < 1e-3) %>% 
  filter(grepl("^Saposin$|^Immunoglobulin-like domain$|^Sodium:dicarboxylate symporter$|Sodium/potassium-transporting ATPase subunit beta superfamily", interpro_description)) %>% 
  mutate(class = ifelse(grepl("Saposin", interpro_description), "saposin domains", "Sodium:dicarboxylate\n symporter"),
         class = ifelse(grepl("^Immunoglobulin-like domain", interpro_description), "immunoglobulin domains", class),
         class = ifelse(grepl("Sodium/potassium-transporting ATPase", interpro_description), "Sodium/potassium-transporting\n ATPase domains", class))%>% 
  ggplot(aes(y = class, x = log2(odds_ratio), size = -log10(adj.p.val), colour = glycan_type)) +
  #geom_point(shape = 15) +
  ggbeeswarm::geom_beeswarm(cex = 4)+
  geom_vline(xintercept = 0, linetype = 3) +
  scale_colour_manual(values = mycolors) +
  scale_size(range = c(2.5, 6)) +
  labs(y = "")

save(domain_enrichment_N, file =paste0("data/paper/enrichments/", Sys.Date(),"_domain_ORA_Nglyco.RData"))
```


## O-glyco


```{r}
domain_enrichment_O <- res_mousebrain_fractionated_Oglyco$psm  %>%
  distinct(Protein.ID, Gene, Peptide, Observed.Modifications, glycan_type, mass, Protein.Start, Protein.End) %>%
  inner_join(ipro, by = c("Protein.ID" = "uniprot_gn_id"), multiple = "all") %>%
  mutate(in_domain = ifelse(Protein.Start > interpro_start & Protein.Start < interpro_end, TRUE, FALSE)) %>%
  filter(!is.na(interpro_description) & !is.na(interpro_start)) %>%
  select(Protein.ID, Peptide, glycan_type, interpro_description, in_domain) %>%
  filter(in_domain == T) %>%
  mutate(siteID = paste0(Protein.ID, "_", Peptide)) %>%
  mutate(n_sites = length(unique(siteID))) %>%
  group_by(glycan_type) %>%
  mutate(n_glycan = length(unique(siteID))) %>%
  group_by(interpro_description) %>%
  mutate(n_domain = length(unique(siteID))) %>%
  group_by(glycan_type, interpro_description) %>%
  mutate(n_type_domain = length(unique(siteID))) %>%
  ungroup() %>%
  distinct(glycan_type, interpro_description, n_sites, n_glycan, n_domain, n_type_domain) %>%
  rowwise() %>%
  mutate(
    FT = fisher.test(x = matrix(
      c(
        n_type_domain,
        n_glycan - n_type_domain,
        n_domain - n_type_domain,
        n_sites - n_glycan - n_domain + n_type_domain
      ),
      nrow = 2, byrow = T
    ))$p.value,
    odds_ratio = fisher.test(x = matrix(
      c(
        n_type_domain,
        n_glycan - n_type_domain,
        n_domain - n_type_domain,
        n_sites - n_glycan - n_domain + n_type_domain
      ),
      nrow = 2, byrow = T
    ))$estimate
  ) %>%
  mutate(
    adj.p.val = p.adjust(FT),
    hit = ifelse(adj.p.val < 0.05, "hit (adj.p < 0.05)", "no hit (adj.p > 0.05)")
  )

save(domain_enrichment_O, file = paste0("data/paper/enrichments/", Sys.Date(),"_domainenrichment_O-glyco.RData"))
```

```{r}

```



