---
title: "Compare glycosylation profile of sites of one protein"
output:
  html_document:
    keep_md: yes
    toc: yes
    theme: united
    code_folding: hide
editor_options: 
  chunk_output_type: inline
---

# General settings

```{r setup}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  include = TRUE,
  cache = TRUE,
  cache.lazy = FALSE,
  eval = TRUE,
  fig.width = 4 * (1 + sqrt(5)) / 2, 
  fig.height = 4,
  dpi = 700
)
knitr::opts_knit$set(root.dir = "~/Documents/Glycoproteomics/")
```

## Packages

```{r, message=F, warning =F, include=}
library(tidyverse)
library(ggplot2); theme_set(cowplot::theme_cowplot(font_size = 15))
library("reshape2")
library(ggrepel)
library(knitr)
library(ggvenn)
library(Biostrings)

mutate <- dplyr::mutate
select <- dplyr::select
group_by <- dplyr::group_by

#source("~/Documents/generic_functions.R")
```

```{r}
options(ggplot2.discrete.colour= c("orange3", "darkslateblue", "darkred", "darkgreen", "darkgrey", "darkviolet"))
options(ggplot2.discrete.fill= c("orange3", "darkslateblue", "darkred", "darkgreen", "darkgrey", "darkviolet"))

order <- c("sialylated", "fucosylated", "high mannose", "complex/hybrid", "phospho", "paucimannose", "small")
```


# Functions

```{r}
pairwise_correlation <- function(df, input, perm) {
  mean_corr_df <- df %>%
    distinct(Protein.ID, Gene, n_position, Observed.Modifications) %>%
    dcast(Protein.ID + Gene + n_position ~ Observed.Modifications, fun.aggregate = length) %>%
    group_by(Protein.ID, Gene) %>%
    nest() %>%
    mutate(mean_corr = map(data, function(df) {
      # prepare matrix composed of all psotions per protein
      t <- df %>%
        melt(id.vars = "n_position") %>%
        acast(variable ~ n_position)
      # convert to correlation matrix
      t2 <- cor(t, method = "kendall")
      # remove correlation matrix as it messes with mean
      diag(t2) <- NA
      # back and forth conversion
      t3 <- as.data.frame(t2)%>% 
        rownames_to_column("site1") %>%  melt(id.vars = c("site1"), variable.name = "site2")
    })) %>%
    select(-data) %>%
    unnest() %>% 
    mutate(
      corr = as.numeric(value),
      input = input,
      perm = perm
    )
}

pairwise_correlation_random <- function(df, input, perm) {
  set.seed(4)
  mean_corr_df <- df %>%
    distinct(Protein.ID, Gene, n_position, Observed.Modifications) %>%
    dcast(Protein.ID + Gene + n_position ~ Observed.Modifications, fun.aggregate = length) %>%
    mutate(ID = paste(Protein.ID, Gene, n_position, sep = "_")) %>%
    select(-Protein.ID, -Gene, -n_position) %>%
    transform(ID = sample(ID)) %>%
    separate(ID, into = c("Protein.ID", "Gene", "n_position"), sep = "_") %>%
    group_by(Protein.ID, Gene) %>%
    nest() %>%
    mutate(mean_corr = map(data, function(df) {
      # prepare matrix composed of all psotions per protein
      t <- df %>%
        melt(id.vars = "n_position") %>%
        acast(variable ~ n_position)
      # convert to correlation matrix
      t2 <- cor(t, method = "kendall")
      # remove correlation matrix as it messes with mean
      diag(t2) <- NA
      # back and forth conversion
      t3 <- as.data.frame(t2)%>% 
        rownames_to_column("site1") %>%  melt(id.vars = c("site1"), variable.name = "site2")
    })) %>%
    select(-data) %>%
    unnest() %>% 
    mutate(
      corr = as.numeric(value),
      input = input,
      perm = perm
    )
}
```

# Load data

```{r}
load("data/paper/processed/2023-05-16_mousebrain_fractionated_Nglyco_psm_processed.RData")
load("data/paper/processed/2023-05-16_mousebrain_fractionated_Oglyco_psm_processed.RData")
```

# Site correlation analysis

This chunk is not executed per default, as it takes several minutes!

```{r, eval =F}
# only do analysis for proteins with at least two sites
more_than_1site <- res_mousebrain_fractionated_Nglyco$psm %>% 
  distinct(Protein.ID, n_position) %>% 
  group_by(Protein.ID) %>% 
  count() %>% 
  filter(n > 1)

# get correaltion for all glycoforms or only larger classes/types
site_corr_obsmod <- res_mousebrain_fractionated_Nglyco$psm %>%
  filter(Protein.ID %in% more_than_1site$Protein.ID) %>%
  pairwise_correlation("everything", "true") %>%
  bind_rows(res_mousebrain_fractionated_Nglyco$psm %>%
    filter(!(glycan_type %in% c("small", "paucimannose", "phospho", "high mannose"))) %>%
    filter(Protein.ID %in% more_than_1site$Protein.ID) %>%
    pairwise_correlation("larger glycans", "true")) %>%
  bind_rows(res_mousebrain_fractionated_Nglyco$psm %>%
    filter(Protein.ID %in% more_than_1site$Protein.ID) %>%
    pairwise_correlation_random("everything", "random")) %>%
  bind_rows(res_mousebrain_fractionated_Nglyco$psm %>%
    filter(Protein.ID %in% more_than_1site$Protein.ID) %>%
    filter(!(glycan_type %in% c("small", "paucimannose", "phospho", "high mannose"))) %>%
    pairwise_correlation_random("larger glycans", "random"))

#save(site_corr_obsmod, file = paste0("data/paper/site_level_results/", Sys.Date(), "_glycositecorrelation_obsmod.RData"))
```


```{r}
load("data/paper/site_level_results/2023-05-16_glycositecorrelation_obsmod.RData")

site_corr_obsmod %>%
  ggplot(aes(x= perm, y = corr, colour =perm)) +
  # geom_histogram(position = "dodge") +
  ggforce::geom_sina(alpha = 1) +
  geom_boxplot(colour = "black", fill = NA) +
  facet_wrap(~input) +
  labs(y = "correlation of sites/protein", x = "data (per glycan composition)")
```

# Comparison to phosphorylation data

```{r}
mouse_psites <- read_tsv("/Users/burtsche/Documents/uniprot/230203_uniprot_mouse_psites.tsv") %>% 
  distinct(Protein.ID = Entry, modification_info = `Modified residue`) %>% 
  mutate(mod = str_extract_all(modification_info, 'MOD_RES \\d+; /note=\\"Phospho\\w+\\";')) %>% 
  unnest(cols = c(mod)) %>% 
  separate(mod, into = c("mod", "type"), sep = "/")%>% 
  mutate(psite_position= as.numeric(str_extract(mod, "\\d+")))
```


```{r}
# N-glycosylation
 res_mousebrain_fractionated_Nglyco$psm  %>% 
  distinct(Protein.ID, n_position, glycan_type) %>% 
  full_join(mouse_psites %>% distinct(Protein.ID, psite_position), by = "Protein.ID", multiple = "all") %>% 
  mutate(close = ifelse(n_position -10 < psite_position &  psite_position < n_position + 10, "psite closer than 5 aa", "no")) %>%
  filter(!is.na(psite_position) & !is.na(glycan_type)) %>% 
  group_by(glycan_type, close) %>% 
  summarise(a = n()) %>% 
  mutate(freq = a/sum(a)*100) %>% 
  filter(close == "psite closer than 5 aa") %>% 
  mutate(glycan_type = factor(glycan_type, levels = order)) %>% 
ggplot(aes(x = close, y = freq, fill = glycan_type)) +
  geom_bar(stat = "identity", pos = "dodge") +
  scale_fill_brewer(palette = "Set1") +
  labs(y = "# glycopeptides with close psite [%]", x = "")

# O-glycosylation
 res_mousebrain_fractionated_Oglyco$psm  %>% 
  distinct(Protein.ID, Protein.Start, Protein.End, mass)%>% 
  mutate(bin = cut(mass, breaks = seq(0, 8000, 500))) %>% 
  group_by(bin) %>% 
  mutate(bin_size = n()) %>% 
  ungroup() %>% 
  left_join(mouse_psites %>% distinct(Protein.ID, psite_position), by = "Protein.ID")%>% 
  mutate(close = ifelse(Protein.Start-5 < psite_position &  psite_position < Protein.End+5, "psite closer than 5 aa", "no")) %>% 
  filter(!is.na(psite_position) & !is.na(bin)) %>% 
  group_by(bin,bin_size, close) %>% 
  summarise(a = n()) %>% 
  mutate(freq = a/bin_size*100) %>% 
  filter(close == "psite closer than 5 aa" & bin_size > 5) %>% 
  ggplot(aes(x = close, y = freq, fill = bin)) +
  geom_bar(stat = "identity", pos = "dodge") +
  scale_fill_viridis_d("mass bin", direction = -1, option = "A") +
  labs(y = "# glycopeptides with close psite [%]", x = "")

 res_mousebrain_fractionated_Oglyco$psm  %>% 
  distinct(Protein.ID, Protein.Start, Protein.End, glycan_type)%>% 
  group_by(glycan_type) %>% 
  mutate(bin_size = n()) %>% 
  ungroup() %>% 
  left_join(mouse_psites %>% distinct(Protein.ID, psite_position), by = "Protein.ID")%>% 
  mutate(close = ifelse(Protein.Start-5 < psite_position &  psite_position < Protein.End+5, "psite closer than 5 aa", "no")) %>% 
  filter(!is.na(psite_position) & !is.na(glycan_type)) %>% 
  group_by(glycan_type,bin_size, close) %>% 
  summarise(a = n()) %>% 
  mutate(freq = a/bin_size*100) %>% 
  filter(close == "psite closer than 5 aa" & bin_size > 5) %>% 
  mutate(glycan_type = factor(glycan_type, levels = c(order, "sulfated"))) %>% 
  ggplot(aes(x = close, y = freq, fill = glycan_type)) + 
  geom_bar(stat = "identity", pos = "dodge") +
  scale_fill_brewer(palette = "Set1") +
  labs(y = "# glycopeptides with close psite [%]", x = "")

```
