---
title: "Initial processing of glycoproteomics datasets"
output:
  html_document:
    keep_md: yes
    toc: yes
    theme: united
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

# General settings

```{r setup}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  include = TRUE,
  cache = TRUE,
  cache.lazy = FALSE,
  eval = TRUE,
  fig.width = 4 * (1 + sqrt(5)) / 2, 
  fig.height = 4,
  dpi = 700
)
knitr::opts_knit$set(root.dir = "/Users/burtsche/Documents/Glycoproteomics/")
```

## Packages

```{r, message=F, warning =F, include=}
library(tidyverse)
library(ggplot2); theme_set(cowplot::theme_cowplot(font_size = 15))
library("reshape2")
library(ggrepel)
library(knitr)
library(ggvenn)

mutate <- dplyr::mutate
select <- dplyr::select
group_by <- dplyr::group_by
```

```{r}
options(ggplot2.discrete.colour= c("orange3", "darkslateblue", "darkred", "darkgreen", "darkgrey", "darkviolet"))
options(ggplot2.discrete.fill= c("orange3", "darkslateblue", "darkred", "darkgreen", "darkgrey", "darkviolet"))
```

# Functions

```{r}

glyco_psm_processing <- function(path, dataset, species){
  
  psm <- read_tsv(path, col_types = cols()) %>% 
    mutate(dataset = dataset, species = species)
  
  # deal wit column name bugs
  colnames(psm) <- gsub(" ", "\\.", colnames(psm))

  psm <- psm %>%
    mutate(
      modification = ifelse(grepl("N\\(", Assigned.Modifications), "glycosylation", "unmodified"),
      glycosylation = str_extract_all(Assigned.Modifications, "\\d+N"),
      n_position = as.numeric(str_extract(glycosylation, "\\d+")) + Protein.Start - 1,
      # add mass bin information
      mass = str_extract(Observed.Modifications, " .+$"),
      mass = as.numeric(str_replace(mass, " % ", "")),
      # bin = cut_interval(mass, n = 10),
      bin = cut(mass, breaks = seq(0, 8000, 500))
      # add glycan group information
    ) %>% 
    separate(Observed.Modifications, into = c("glycan_content", "modification_mass"), sep = " % ", remove = F) %>%
    separate(glycan_content, into = c("hexnac", "hexnac_content", "hex", "hex_content", "end"), sep = "\\(|\\)", extra = "merge", remove = FALSE) %>%
    mutate(
      hexnac_content = as.numeric(hexnac_content),
      hex_content = as.numeric(hex_content),
      end = ifelse(is.na(end), "", end)
    ) %>%
    mutate(glycan_type = case_when(
      grepl("Phospho", glycan_content) ~ "phospho",
      grepl("NeuAc", glycan_content) ~ "sialylated",
      grepl("Fuc", glycan_content) ~ "fucosylated",
      hexnac_content == 2 & hex_content > 3 & end == "" ~ "high mannose",
      hexnac_content == 2 & hex_content %in% 1:3 & end == "" ~ "paucimannose",
      hexnac_content <= 2 & hex == "" & end == "" ~ "small",
      TRUE ~ "complex/hybrid"
    ))
  
  
  psm_glyco <- psm %>% 
    filter(modification == "glycosylation")
  
  summary <- data.frame(n_proteins = length(unique(psm_glyco$Protein.ID)),
                        n_peptides = nrow(distinct(psm_glyco, Protein.ID, Modified.Peptide)),
                        n_sites = nrow(distinct(psm_glyco, Protein.ID, n_position)),
                        dataset = dataset,
                        species = species
                        )
  
  
  
  res <- list("psm" = psm_glyco,"summary" = summary, "psm_total" = psm)

}

```

#1. N-glyco

## Optimization data 

### lysis method

```{r, eval =F}
psm_lysis_methods <- glyco_psm_processing("data/paper/psm_files/labelfree/lysis_methods/230403_HEK_SDS_psm.tsv", 
                                          "LF_HEK_lysismethods", 
                                          "HEK_lysismethods")

psm <- psm_lysis_methods$psm %>%
  as.data.frame() %>%
  mutate(
    expID = str_extract(Spectrum, "HEK.+[lysis, IPA, SDS]"),
    lysis_method = ifelse(grepl("SDS", expID), "SDS\nlysis", "adapted\nlysis")
  ) %>%
  group_by(lysis_method) %>%
  mutate(replicate = as.integer(as.factor(expID))) %>%
  mutate(glycosylation = as.character(glycosylation)) %>% 
  select(-expID)

psm_total <- psm_lysis_methods$psm_total %>%
  as.data.frame() %>%
    mutate(
    expID = str_extract(Spectrum, "HEK.+[lysis, IPA, SDS]"),
    lysis_method = ifelse(grepl("SDS", expID), "SDS\nlysis", "adapted\nlysis")
  ) %>%
  group_by(lysis_method) %>%
  mutate(replicate = as.integer(as.factor(expID))) %>%
  mutate(glycosylation = as.character(glycosylation)) %>% 
  select(-expID)

summary <- psm %>%
  mutate(pepID = paste0(Protein.ID, "_", Modified.Peptide),
         siteID = paste0(Protein.ID, "_", n_position)) %>%
  select(Protein.ID, pepID, siteID)%>%
  summarise(
    n_glycoproteins = n_distinct(Protein.ID),
    n_glycopeptides = n_distinct(pepID),
    n_glycosites = n_distinct(siteID)
  ) %>%
  mutate(dataset = "LF_HEK_lysismethods")

res_lysismethods <- list("psm" = psm, "summary" = summary, "psm_total" = psm_total)
save(res_lysismethods, file = paste0("data/paper/processed/", Sys.Date(),"_HEK_lf_lysismethods_3rep_psm_processed.RData"))
```

### scan ranges

```{r, eval =F}
psm_scan_ranges <- glyco_psm_processing("data/paper/psm_files/labelfree/scan_ranges/HeLa_scan_range_good_psm.tsv", "LF_HeLa_scanranges", "HeLa_scanranges")

psm_scan_ranges$psm %>%  
  mutate(scan_range = str_extract(Spectrum, "HeLa_1p5mg_glyco_\\d+-\\d+"), 
         replicate = str_extract(Spectrum, "HeLa_1p5mg_glyco_\\d+-\\d+_\\d"),
         replicate = ifelse(is.na(replicate), "1", str_replace(replicate, "HeLa_1p5mg_glyco_\\d+-\\d+_", ""))) %>%
  group_by(scan_range, replicate) %>% 
  count()

psm_scan_ranges$psm_total %>%  
    mutate(scan_range = str_extract(Spectrum, "HeLa_1p5mg_glyco_\\d+-\\d+"), 
         replicate = str_extract(Spectrum, "HeLa_1p5mg_glyco_\\d+-\\d+_\\d"),
         replicate = ifelse(is.na(replicate), "1", str_replace(replicate, "HeLa_1p5mg_glyco_\\d+-\\d+_", ""))) %>%
  group_by(scan_range, modification) %>% 
  count()

psm <- psm_scan_ranges$psm %>%
  as.data.frame() %>%
  mutate(glycosylation = as.character(glycosylation)) %>%
  mutate(
    scan_range = str_extract(Spectrum, "HeLa_1p5mg_glyco_\\d+-\\d+"),
    replicate = str_extract(Spectrum, "HeLa_1p5mg_glyco_\\d+-\\d+_\\d"),
    replicate = ifelse(is.na(replicate), "1", str_replace(replicate, "HeLa_1p5mg_glyco_\\d+-\\d+_", ""))
  )

psm_total <- psm_scan_ranges$psm_total %>%
  as.data.frame() %>%
  mutate(glycosylation = as.character(glycosylation)) %>% 
  mutate(
    scan_range = str_extract(Spectrum, "HeLa_1p5mg_glyco_\\d+-\\d+"),
    replicate = str_extract(Spectrum, "HeLa_1p5mg_glyco_\\d+-\\d+_\\d"),
    replicate = ifelse(is.na(replicate), "1", str_replace(replicate, "HeLa_1p5mg_glyco_\\d+-\\d+_", ""))
  )

summary <- psm %>%
  mutate(pepID = paste0(Protein.ID, "_", Modified.Peptide),
         siteID = paste0(Protein.ID, "_", n_position)) %>%
  group_by(scan_range, replicate) %>% 
  summarise(
    n_glycoproteins = n_distinct(Protein.ID),
    n_glycopeptides = n_distinct(pepID),
    n_glycosites = n_distinct(siteID)
  ) %>%
  mutate(dataset = "LF_HeLa_scanranges")

res_scanranges <- list("psm" = psm, "summary" = summary, "psm_total" = psm_total)
save(res_scanranges, file =paste0("data/paper/processed/", Sys.Date(),"_Hela_lf_scanranges_3rep_psm_processed.RData"))
```

##LF N-glyco Single-shot mouse brain dataset

```{r, eval =F}
psm_species <- glyco_psm_processing("data/paper/psm_files/labelfree/20230320_Mouse_brain_singleshots_3rep_psm.tsv", 
                                    "LF_brains_singleshot", 
                                    "mouse\nbrain_ss")
psm <- psm_species$psm %>%
  as.data.frame() %>%
  mutate(glycosylation = as.character(glycosylation))

psm_total <- psm_species$psm_total %>%
  as.data.frame() %>%
  mutate(glycosylation = as.character(glycosylation))

summary <- psm %>%
  mutate(pepID = paste0(Protein.ID, "_", Modified.Peptide),
         siteID = paste0(Protein.ID, "_", n_position)) %>%
  select(Protein.ID, pepID, siteID)%>%
  summarise(
    n_glycoproteins = n_distinct(Protein.ID),
    n_glycopeptides = n_distinct(pepID),
    n_glycosites = n_distinct(siteID)
  ) %>%
  mutate(dataset = "LF_brains_singleshot")

res_singleshot <- list("psm" = psm, "summary" = summary, "psm_total" = psm_total)

save(res_singleshot, file =paste0("data/paper/processed/", Sys.Date(),"_Mouse_brain_lf_singleshot_psm_processed.RData"))
```

## LF singleshots 3best runs N-glyco Human cell lines

```{r, eval=F}
psm_species <- glyco_psm_processing("data/paper/psm_files/labelfree/HEK_HeLa_glyco_3best_largedatabase_psm.tsv", "mixed", "mixed")

# map file name to metadata info 
mapping_temp <- data.frame(
  data = c("HeLa_R1", "HeLa_R2", "HeLa_R3", "HEK_R1", "HEK_R2", "HEK_R3"),
  ID = c(
    "Lara_220801_S3233_CP_Glyco_HeLa_HCD40", 
    "Lara_220722_S3229_CP_HeLa_glyco_5mg_PBA", 
    "Lara_220801_S3233_CP_Glyco_HeLa_steppedHCD",
    "Lara_220802_S3233_CP_Glyco_HEK_HCD40", 
    "Lara_220818_S3233_CP_HEK_noMg_40ACN", 
    "Lara_220818_S3233_CP_HEK_noMg_40ACN_IPA"
  ),
  species = "human\ncell line"
)

psm <- psm_species$psm %>%
  as.data.frame() %>%
  mutate(dataset = str_extract(Spectrum, "Lara[^\\.]*")) %>%
  select(-species) %>%
  left_join(mapping_temp, by = c("dataset" = "ID")) %>%
  mutate(glycosylation = as.character(glycosylation))

psm_total <- psm_species$psm_total %>%
  as.data.frame() %>%
  mutate(dataset = str_extract(Spectrum, "Lara[^\\.]*")) %>%
  select(-species) %>%
  left_join(mapping_temp, by = c("dataset" = "ID"))

summary <- psm %>%
  mutate(pepID = paste0(Protein.ID, "_", Modified.Peptide),
         siteID = paste0(Protein.ID, "_", n_position)) %>%
  select(data, Protein.ID, pepID, siteID)%>%
  group_by(data) %>%
  summarise(
    n_glycoproteins = n_distinct(Protein.ID),
    n_glycopeptides = n_distinct(pepID),
    n_glycosites = n_distinct(siteID)
  ) %>%
  mutate(dataset = data, species = str_replace(data, "_R\\d$", ""))

res_celllines <- list("psm" = psm, "summary" = summary, "psm_total" = psm_total)

save(res_celllines, file =paste0("data/paper/processed/",Sys.Date(),"_humancelllines_lf_3best_psm_processed.RData"))
  
```


## LF N-glyco Mouse brain tissue fractionated


```{r, eval=F}
psm_species <- glyco_psm_processing("data/paper/psm_files/labelfree/Mouse_brain_allfiles_final_psm.tsv", "LF_brains", "mouse\nbrain")

psm <- psm_species$psm %>%
  as.data.frame() %>%
  mutate(fraction = str_extract(Spectrum, "F\\d+"), data = "mouse brain fractionated") %>%
  mutate(fraction = factor(fraction, levels = c(paste0("F", seq(1:96)))),
    glycosylation = as.character(glycosylation))

psm_total <- psm_species$psm_total %>%
  as.data.frame() %>%
  mutate(fraction = str_extract(Spectrum, "F\\d+"), data = "mouse brain fractionated") %>%
  mutate(fraction = factor(fraction, levels = c(paste0("F", seq(1:96)))))

summary <- psm %>%
  mutate(pepID = paste0(Protein.ID, "_", Modified.Peptide),
         siteID = paste0(Protein.ID, "_", n_position)) %>%
  select(data, Protein.ID, pepID, siteID)%>%
  group_by(data) %>%
  summarise(
    n_glycoproteins = n_distinct(Protein.ID),
    n_glycopeptides = n_distinct(pepID),
    n_glycosites = n_distinct(siteID)
  ) %>%
  mutate(dataset = data, species = str_replace(data, "_R\\d$", ""))

res_mousebrain_fractionated_Nglyco <- list("psm" = psm, "summary" = summary, "psm_total" = psm_total)

save(res_mousebrain_fractionated_Nglyco, file = paste0("data/paper/processed/",Sys.Date(),"_mousebrain_fractionated_Nglyco_psm_processed.RData"))
  
```

<!-- ### Collapse preprocessed data for human and mice -->

<!-- ```{r, eval =F} -->
<!-- load("data/paper/processed/230320_HEK_HeLa_glyco_3best_runs_largedatabase_psm_processed.RData") -->
<!-- psm_human <- res_species$psm %>% as.data.frame() -->
<!-- psm_human_summary <- res_species$summary %>% as.data.frame() -->
<!-- psm_human_total <- res_species$psm_total %>% as.data.frame() -->

<!-- load("data/paper/processed/230320_Mouse_brain_all_psm_processed.RData") -->
<!-- psm_mouse <- res_species$psm %>% as.data.frame() -->
<!-- psm_mouse_summary <- res_species$summary %>% as.data.frame() -->
<!-- psm_mouse_total <- res_species$psm_total %>% as.data.frame() -->

<!-- psm_species <- bind_rows(psm_human, psm_mouse) -->
<!-- summary <- bind_rows(psm_human_summary, psm_mouse_summary) -->
<!-- psm_total <- bind_rows(psm_human_total, psm_mouse_total) -->

<!-- res_species <- list("psm" = psm_species, "summary" = summary, "psm_total" = psm_total) -->

<!-- save(res_species, file ="data/paper/processed/230213_allspecies_psm_processed.RData") -->
<!-- ``` -->

## Quant N-glyco microbiome mouse brain

```{r, eval = F}
psm_species <- glyco_psm_processing("data/paper/psm_files/TMT/Mouse_brain_GF_Mono_8c_glyco_1protpergene_psm.tsv", 
                                    "TMT_microbiome_mousebrain_Nglyco", 
                                    "microbiome_mouse\nbrain_Nglyco")


psm <- psm_species$psm %>%
  as.data.frame() %>%
  mutate(glycosylation = as.character(glycosylation))

psm_total <- psm_species$psm_total %>%
  as.data.frame() %>%
  mutate(glycosylation = as.character(glycosylation))

summary <- psm %>%
  mutate(pepID = paste0(Protein.ID, "_", Modified.Peptide),
         siteID = paste0(Protein.ID, "_", n_position)) %>%
  select(Protein.ID, pepID, siteID)%>%
  summarise(
    n_glycoproteins = n_distinct(Protein.ID),
    n_glycopeptides = n_distinct(pepID),
    n_glycosites = n_distinct(siteID)
  ) %>%
  mutate(dataset = "microbiome_mouse\nbrain_Nglyco")

res_microbiome_mousebrain_Nglyco <- list("psm" = psm, "summary" = summary, "psm_total" = psm_total)

save(res_microbiome_mousebrain_Nglyco, file =paste0("data/paper/processed/",Sys.Date(),"_microbiome_mousebrain_Nglyco_psm_processed.RData"))
```

#2. O-glyco

## LF frac mousebrain

```{r, eval =F}
psm <- read_csv("data/paper/psm_files/TMT/Mouse_brain_allF_O-glyco_filtered.csv")%>% 
    mutate(dataset = "O-glycosylation", species = "mouse\nbrain")

  # deal wit column name bugs
  colnames(psm) <- gsub(" ", "\\.", colnames(psm))

  psm_glyco <- psm %>%
    # remove N-glycosylation
    filter(!grepl("N.{1}T|N.{1}S", Peptide)) %>%
    filter(!(grepl("N.$", Peptide) & Next.AA %in% c("S", "T"))) %>%
    filter(!is.na(Observed.Modifications) & Observed.Modifications != "no target matches") %>%
    mutate(
      glycosylation = str_extract_all(Assigned.Modifications, "\\d+N"),
      n_position = as.numeric(str_extract(glycosylation, "\\d+")) + Protein.Start - 1,
      # add mass bin information
      mass = str_extract(Observed.Modifications, " .+$"),
      mass = as.numeric(str_replace(mass, " % ", "")),
      # bin = cut_interval(mass, n = 10),
      bin = cut(mass, breaks = seq(100, plyr::round_any(max(mass), 500), 100))
      # add glycan group information
    ) %>%
    separate(Observed.Modifications, into = c("glycan_content", "modification_mass"), sep = " % ", remove = F) %>%
    separate(glycan_content, into = c("hexnac", "hexnac_content", "hex", "hex_content", "end"), sep = "\\(|\\)", extra = "merge", remove = FALSE) %>%
    mutate(
      hexnac_content = as.numeric(hexnac_content),
      hex_content = as.numeric(hex_content),
      end = ifelse(is.na(end), "", end)
    ) %>%
    mutate(glycan_type = case_when(
      grepl("Phospho", glycan_content) ~ "phospho",
      grepl("NeuAc", glycan_content) ~ "sialylated",
      grepl("Fuc", glycan_content) ~ "fucosylated",
      grepl("Sulf", glycan_content) ~ "sulfated",
      hexnac_content == 2 & hex_content > 3 & end == "" ~ "high mannose",
      hexnac_content == 2 & hex_content %in% 1:3 & end == "" ~ "paucimannose",
      hexnac_content <= 2 & hex == "" & end == "" ~ "small",
      TRUE ~ "complex/hybrid"
    )) %>% 
    select(-n_position)
  

  
  summary <- psm_glyco %>%
  mutate(pepID = paste0(Protein.ID, "_", Modified.Peptide, "_", Observed.Modifications)) %>%
  dplyr::select(Protein.ID, pepID)%>%
  summarise(
    n_glycoproteins = n_distinct(Protein.ID),
    n_glycopeptides = n_distinct(pepID)
  ) %>% 
    mutate(dataset = "O-glycosylation",
                        species = "mouse\nbrain")
  
  
  res_mousebrain_fractionated_Oglyco <- list("psm" = psm_glyco, "summary" = summary)

 
save(res_mousebrain_fractionated_Oglyco, file = paste0("data/paper/processed/",Sys.Date(),"_mousebrain_fractionated_Oglyco_psm_processed.RData"))
```
